import { MAX_ROUND, MIN_ROUND, type SchemeDraft } from './progress';
import { chooseScheme, setSchemeChecked, type ChosenScheme } from './scheme';
import type { PlayerKey, PlayerProgress } from './twoPlayer';

export type OnlineGameStatus = 'lobby' | 'active' | 'finished' | 'closed';
export type OnlineGamePhase = 'reveal' | 'scoring';

export const MAX_NICKNAME_LENGTH = 24;

/** Full state of one seat — contains that player's secrets. */
export type OnlineSeatState = {
	nickname: string;
	/** SHA-256 of the seat token; the plain token only lives on the client. */
	tokenHash: string;
	progress: PlayerProgress;
	/** Toggleable intent during a Reveal phase — committed when the leader advances to Scoring. */
	revealIntent: boolean;
	/** Ids of the drawn scheme cards; private to this seat, persisted for reconnects. */
	drawnSchemeIds: string[];
};

export type RoundSnapshot = { player1: number; player2: number };

/** Compact end-of-game summary, written at `game-finished` so statistics never need event payloads. */
export type ResultSummary = {
	winner: PlayerKey | 'draw';
	finalVp: RoundSnapshot;
	roundsPlayed: number;
	season: string | null;
	missionId: string | null;
	factions: { player1: string | null; player2: string | null };
};

/** Awaiting leader approval; the token is generated by the joining player, only its hash travels to the server. */
export type PendingJoin = { nickname: string; tokenHash: string };

export type OnlineGameState = {
	id: string;
	status: OnlineGameStatus;
	player1: OnlineSeatState;
	player2: OnlineSeatState | null;
	pendingJoin: PendingJoin | null;
	season: string | null;
	missionId: string | null;
	currentRound: number;
	phase: OnlineGamePhase;
	roundSnapshots: Record<number, RoundSnapshot>;
	winner: PlayerKey | 'draw' | null;
	resultSummary: ResultSummary | null;
	createdAt: string;
	updatedAt: string;
};

/** What one seat is allowed to see of the other. */
export type PublicSeatState = {
	nickname: string;
	factionId: string | null;
	hasScheme: boolean;
	schemeRevealed: boolean;
	/** Only populated when revealed — unrevealed scheme content never travels to the opponent. */
	revealedScheme: ChosenScheme | null;
	checkedObjectiveCounts: Record<string, number>;
};

/** The per-seat filtered view the API returns. */
export type OnlineGameView = {
	id: string;
	status: OnlineGameStatus;
	seat: PlayerKey;
	phase: OnlineGamePhase;
	currentRound: number;
	season: string | null;
	missionId: string | null;
	pendingJoinNickname: string | null;
	roundSnapshots: Record<number, RoundSnapshot>;
	winner: PlayerKey | 'draw' | null;
	/** End-of-game summary — public once the game is finished. */
	resultSummary: ResultSummary | null;
	/** Full own-seat state including secrets. */
	self: OnlineSeatState;
	/** Filtered view of the other seat, or null while it is empty. */
	opponent: PublicSeatState | null;
};

export type OnlineGameEventType =
	| 'game-created'
	| 'join-requested'
	| 'join-accepted'
	| 'join-denied'
	| 'faction-drafted'
	| 'schemes-drawn'
	| 'scheme-chosen'
	| 'scheme-deleted'
	| 'mission-selected'
	| 'game-started'
	| 'reveal-intent-toggled'
	| 'phase-changed'
	| 'objective-toggled'
	| 'scheme-box-toggled'
	| 'round-snapshotted'
	| 'game-finished'
	| 'game-closed';

/** Trimmed nickname, or null when empty/too long. */
export function normalizeNickname(raw: string): string | null {
	const trimmed = raw.trim();
	if (trimmed.length < 1 || trimmed.length > MAX_NICKNAME_LENGTH) return null;
	return trimmed;
}

function createEmptyProgress(): PlayerProgress {
	return {
		checkedObjectiveCounts: {},
		scheme: null,
		schemeDraft: { factionId: null, intelligence: null },
		schemeRevealed: false
	};
}

export function createEmptySeat(nickname: string, tokenHash: string): OnlineSeatState {
	return {
		nickname,
		tokenHash,
		progress: createEmptyProgress(),
		revealIntent: false,
		drawnSchemeIds: []
	};
}

export function createOnlineGame(
	id: string,
	leaderNickname: string,
	leaderTokenHash: string,
	createdAt: string
): OnlineGameState {
	return {
		id,
		status: 'lobby',
		player1: createEmptySeat(leaderNickname, leaderTokenHash),
		player2: null,
		pendingJoin: null,
		season: null,
		missionId: null,
		currentRound: MIN_ROUND,
		phase: 'reveal',
		roundSnapshots: {},
		winner: null,
		resultSummary: null,
		createdAt,
		updatedAt: createdAt
	};
}

function updateSeat(
	state: OnlineGameState,
	seat: PlayerKey,
	updater: (s: OnlineSeatState) => OnlineSeatState
): OnlineGameState {
	const current = state[seat];
	if (!current) return state;
	return { ...state, [seat]: updater(current) };
}

/** Which seat owns a given (already hashed) token, if any. */
export function seatForTokenHash(state: OnlineGameState, tokenHash: string): PlayerKey | null {
	if (state.player1.tokenHash === tokenHash) return 'player1';
	if (state.player2?.tokenHash === tokenHash) return 'player2';
	return null;
}

// --- lobby: join flow ---

export function canRequestJoin(state: OnlineGameState): boolean {
	return state.status === 'lobby' && !state.player2 && !state.pendingJoin;
}

export function requestJoin(
	state: OnlineGameState,
	nickname: string,
	tokenHash: string
): OnlineGameState {
	if (!canRequestJoin(state)) return state;
	return { ...state, pendingJoin: { nickname, tokenHash } };
}

/** Seat 2 takes over the pending request's nickname and token hash. */
export function acceptJoin(state: OnlineGameState): OnlineGameState {
	if (state.status !== 'lobby' || state.player2 || !state.pendingJoin) return state;
	return {
		...state,
		player2: createEmptySeat(state.pendingJoin.nickname, state.pendingJoin.tokenHash),
		pendingJoin: null
	};
}

export function denyJoin(state: OnlineGameState): OnlineGameState {
	if (!state.pendingJoin) return state;
	return { ...state, pendingJoin: null };
}

// --- lobby: setup ---

/** Faction/scheme setup unlocks only after both seats are filled, and ends with the lobby. */
export function canEditSetup(state: OnlineGameState): boolean {
	return state.status === 'lobby' && state.player2 !== null;
}

export function canSelectMission(state: OnlineGameState): boolean {
	return state.status === 'lobby' && state.player2 !== null;
}

export function selectMission(
	state: OnlineGameState,
	season: string,
	missionId: string
): OnlineGameState {
	if (!canSelectMission(state)) return state;
	return { ...state, season, missionId };
}

export function setSeatDraft(
	state: OnlineGameState,
	seat: PlayerKey,
	draft: Partial<SchemeDraft>
): OnlineGameState {
	if (!canEditSetup(state)) return state;
	return updateSeat(state, seat, (s) => ({
		...s,
		progress: { ...s.progress, schemeDraft: { ...s.progress.schemeDraft, ...draft } }
	}));
}

export function setSeatDrawnSchemes(
	state: OnlineGameState,
	seat: PlayerKey,
	schemeIds: string[]
): OnlineGameState {
	if (!canEditSetup(state)) return state;
	return updateSeat(state, seat, (s) => ({ ...s, drawnSchemeIds: schemeIds }));
}

export function canDrawSchemes(state: OnlineGameState, seat: PlayerKey): boolean {
	const current = state[seat];
	if (!canEditSetup(state) || !current) return false;
	const { factionId, intelligence } = current.progress.schemeDraft;
	return factionId !== null && intelligence !== null;
}

/** Only cards from the seat's own drawn hand may be chosen. */
export function canChooseSeatScheme(
	state: OnlineGameState,
	seat: PlayerKey,
	schemeId: string
): boolean {
	const current = state[seat];
	if (!canEditSetup(state) || !current) return false;
	const { factionId, intelligence } = current.progress.schemeDraft;
	return factionId !== null && intelligence !== null && current.drawnSchemeIds.includes(schemeId);
}

/** Picks a scheme from the seat's drawn hand and discards the rest of the hand. */
export function chooseSeatScheme(
	state: OnlineGameState,
	seat: PlayerKey,
	schemeId: string
): OnlineGameState {
	if (!canChooseSeatScheme(state, seat, schemeId)) return state;
	const { factionId, intelligence } = state[seat]!.progress.schemeDraft;
	return updateSeat(state, seat, (s) => ({
		...s,
		drawnSchemeIds: [],
		progress: { ...s.progress, scheme: chooseScheme(schemeId, factionId!, intelligence!) }
	}));
}

export function clearSeatScheme(state: OnlineGameState, seat: PlayerKey): OnlineGameState {
	if (!canEditSetup(state)) return state;
	return updateSeat(state, seat, (s) => ({ ...s, progress: { ...s.progress, scheme: null } }));
}

export function canStartGame(state: OnlineGameState): boolean {
	return (
		state.status === 'lobby' &&
		state.missionId !== null &&
		state.player2 !== null &&
		state.player1.progress.scheme !== null &&
		state.player2.progress.scheme !== null
	);
}

export function startGame(state: OnlineGameState): OnlineGameState {
	if (!canStartGame(state)) return state;
	return { ...state, status: 'active', currentRound: MIN_ROUND, phase: 'reveal' };
}

// --- active: rounds & phases ---

export function toggleRevealIntent(state: OnlineGameState, seat: PlayerKey): OnlineGameState {
	if (state.status !== 'active' || state.phase !== 'reveal') return state;
	const current = state[seat];
	if (!current || !current.progress.scheme) return state;
	return updateSeat(state, seat, (s) => ({ ...s, revealIntent: !s.revealIntent }));
}

/** Commits every reveal intent: intended schemes become permanently revealed. */
export function advanceToScoring(state: OnlineGameState): OnlineGameState {
	if (state.status !== 'active' || state.phase !== 'reveal') return state;
	const commit = (seat: OnlineSeatState): OnlineSeatState => {
		const revealed = seat.progress.scheme && seat.revealIntent;
		return {
			...seat,
			revealIntent: false,
			progress: revealed ? { ...seat.progress, schemeRevealed: true } : seat.progress
		};
	};
	return {
		...state,
		player1: commit(state.player1),
		player2: state.player2 ? commit(state.player2) : null,
		phase: 'scoring'
	};
}

/** Objectives are editable only by their owner and only during the Scoring phase. */
export function setSeatObjectiveChecked(
	state: OnlineGameState,
	seat: PlayerKey,
	objectiveId: string,
	checkedCount: number,
	maxCount: number
): OnlineGameState {
	if (state.status !== 'active' || state.phase !== 'scoring') return state;
	const clamped = Math.max(0, Math.min(checkedCount, maxCount));
	return updateSeat(state, seat, (s) => ({
		...s,
		progress: {
			...s.progress,
			checkedObjectiveCounts: { ...s.progress.checkedObjectiveCounts, [objectiveId]: clamped }
		}
	}));
}

/** Scheme boxes are editable only by their owner, only during Scoring, and only once revealed. */
export function canScoreSeatScheme(state: OnlineGameState, seat: PlayerKey): boolean {
	if (state.status !== 'active' || state.phase !== 'scoring') return false;
	const current = state[seat];
	return !!current?.progress.scheme && current.progress.schemeRevealed;
}

export function setSeatSchemeChecked(
	state: OnlineGameState,
	seat: PlayerKey,
	checkedIncrements: number,
	maxIncrements: number
): OnlineGameState {
	if (!canScoreSeatScheme(state, seat)) return state;
	return updateSeat(state, seat, (s) => ({
		...s,
		progress: {
			...s.progress,
			scheme: setSchemeChecked(s.progress.scheme!, checkedIncrements, maxIncrements)
		}
	}));
}

export function bothSchemesRevealed(state: OnlineGameState): boolean {
	const p1 = state.player1;
	const p2 = state.player2;
	const revealed = (seat: OnlineSeatState | null) =>
		!!seat && (!seat.progress.scheme || seat.progress.schemeRevealed);
	return revealed(p1) && revealed(p2);
}

/** Snapshots the current round's VP, then advances; skips the next Reveal phase when nothing is left to reveal. */
export function snapshotAndProceed(state: OnlineGameState, vp: RoundSnapshot): OnlineGameState {
	if (state.status !== 'active' || state.phase !== 'scoring') return state;
	if (state.currentRound >= MAX_ROUND) return state;
	return {
		...state,
		roundSnapshots: { ...state.roundSnapshots, [state.currentRound]: vp },
		currentRound: state.currentRound + 1,
		phase: bothSchemesRevealed(state) ? 'scoring' : 'reveal'
	};
}

export function finishGame(state: OnlineGameState, vp: RoundSnapshot): OnlineGameState {
	if (state.status !== 'active' || state.phase !== 'scoring' || state.currentRound !== MAX_ROUND) {
		return state;
	}
	const revealAll = (seat: OnlineSeatState): OnlineSeatState => {
		if (!seat.progress.scheme) return seat;
		return {
			...seat,
			revealIntent: false,
			progress: { ...seat.progress, schemeRevealed: true }
		};
	};
	const winner: PlayerKey | 'draw' =
		vp.player1 > vp.player2 ? 'player1' : vp.player2 > vp.player1 ? 'player2' : 'draw';
	const factionOf = (seat: OnlineSeatState | null): string | null =>
		seat?.progress.scheme?.factionId ?? seat?.progress.schemeDraft.factionId ?? null;
	const resultSummary: ResultSummary = {
		winner,
		finalVp: vp,
		roundsPlayed: state.currentRound,
		season: state.season,
		missionId: state.missionId,
		factions: { player1: factionOf(state.player1), player2: factionOf(state.player2) }
	};
	return {
		...state,
		roundSnapshots: { ...state.roundSnapshots, [state.currentRound]: vp },
		player1: revealAll(state.player1),
		player2: state.player2 ? revealAll(state.player2) : null,
		winner,
		resultSummary,
		status: 'finished'
	};
}

/** Leader closes/abandons the game — allowed from lobby or active, never overrides finished. */
export function closeGame(state: OnlineGameState): OnlineGameState {
	if (state.status === 'finished' || state.status === 'closed') return state;
	return { ...state, status: 'closed' };
}

// --- visibility ---

export function toPublicSeat(seat: OnlineSeatState): PublicSeatState {
	const { progress } = seat;
	return {
		nickname: seat.nickname,
		factionId: progress.scheme?.factionId ?? progress.schemeDraft.factionId,
		hasScheme: progress.scheme !== null,
		schemeRevealed: progress.schemeRevealed,
		revealedScheme: progress.scheme && progress.schemeRevealed ? progress.scheme : null,
		checkedObjectiveCounts: progress.checkedObjectiveCounts
	};
}

/** The server answers state requests with this per-seat filtered view. */
export function viewForSeat(state: OnlineGameState, seat: PlayerKey): OnlineGameView | null {
	const self = state[seat];
	if (!self) return null;
	const opponent = seat === 'player1' ? state.player2 : state.player1;
	return {
		id: state.id,
		status: state.status,
		seat,
		phase: state.phase,
		currentRound: state.currentRound,
		season: state.season,
		missionId: state.missionId,
		pendingJoinNickname: state.pendingJoin?.nickname ?? null,
		roundSnapshots: state.roundSnapshots,
		winner: state.winner,
		resultSummary: state.resultSummary,
		self,
		opponent: opponent ? toPublicSeat(opponent) : null
	};
}
