import { MAX_ROUND, MIN_ROUND } from './progress';
import { chooseScheme, setSchemeChecked, type ChosenScheme } from './scheme';
import { schemeFactionForArmy } from './faction';
import { pickedArmyFormat, type PickedArmy } from './savedArmy';
import type { ArmyFactionId, ArmyFormat } from './army';
import type { PlayerKey, SeatProgress } from './twoPlayer';

export type OnlineGameStatus = 'lobby' | 'active' | 'finished' | 'closed';
/**
 * `armies` reveals both rosters, `prep` cuts a registered Roster army down to a match list,
 * `setup` chooses Schemes, and `playing` is every round — a round carries no sub-phase, because
 * everything a round needs is editable within it. The preparation steps live in the phase rather
 * than in a status of their own because `cleanup.ts` buckets retention by status literal — a new
 * status would match no bucket and never be collected.
 */
export type OnlineGamePhase = 'armies' | 'prep' | 'setup' | 'playing';

export const MAX_NICKNAME_LENGTH = 24;

/** Full state of one seat — contains that player's secrets. */
export type OnlineSeatState = {
	nickname: string;
	/** SHA-256 of the seat token; the plain token only lives on the client. */
	tokenHash: string;
	/** The army the player registered with; its code is this seat's secret. */
	army: PickedArmy;
	/**
	 * The Standard list this seat actually fields. A Standard registration is its own combat army
	 * from the start; a Roster one is null until the player cuts one down and accepts it.
	 */
	combatArmy: PickedArmy | null;
	/** The copy of the combat army chosen as Leader; null until assigned. */
	leader: SeatLeader | null;
	/** Lobby readiness: this player says they are set to start. Toggled by its own seat only. */
	ready: boolean;
	progress: SeatProgress;
	/** Ids of the drawn scheme cards; private to this seat, persisted for reconnects. */
	drawnSchemeIds: string[];
};

/**
 * A seat's chosen Leader: which copy of the combat army it is, plus the two statistics the
 * initiative roll will need. The server cannot compute those — it loads no army catalogs — so the
 * client declares them, the same ruling army legality already rests on. The entry id stays
 * private; only the statistics are ever published.
 */
export type SeatLeader = {
	entryId: string;
	m: number | null;
	int: number | null;
};

/** Which of a seat's secrets the current point in the game has opened up. */
export type SeatReveal = {
	/** The roster's contents, from the army reveal on. */
	roster: boolean;
	/** The leader's M and INT, from Scheme selection on. */
	leaderStats: boolean;
};

export type RoundSnapshot = { player1: number; player2: number };

/** Compact end-of-game summary, written at `game-finished` so statistics never need event payloads. */
export type ResultSummary = {
	winner: PlayerKey | 'draw';
	finalVp: RoundSnapshot;
	roundsPlayed: number;
	season: string | null;
	missionId: string | null;
	factions: { player1: string | null; player2: string | null };
};

/** Awaiting leader approval; the token is generated by the joining player, only its hash travels to the server. */
export type PendingJoin = { nickname: string; tokenHash: string; army: PickedArmy };

export type OnlineGameState = {
	id: string;
	status: OnlineGameStatus;
	player1: OnlineSeatState;
	player2: OnlineSeatState | null;
	pendingJoin: PendingJoin | null;
	season: string | null;
	missionId: string | null;
	currentRound: number;
	phase: OnlineGamePhase;
	roundSnapshots: Record<number, RoundSnapshot>;
	winner: PlayerKey | 'draw' | null;
	resultSummary: ResultSummary | null;
	createdAt: string;
	updatedAt: string;
};

/**
 * What the opponent's seat card may show: the army's identity, never its code, so
 * nobody can import nobody else's list. The faction is an **army** faction and has
 * nothing to do with `PublicSeatState.factionId`, which is a scheme faction — the two
 * id spaces differ on exactly the monster factions.
 */
export type PublicArmy = {
	name: string;
	factionId: ArmyFactionId;
	format: ArmyFormat;
};

/** What one seat is allowed to see of the other. */
export type PublicSeatState = {
	nickname: string;
	army: PublicArmy;
	/**
	 * The roster's code, once the reveal has happened — null in the lobby, and null forever for a
	 * Standard registration, whose list is the match list and stays secret until deployment.
	 */
	rosterCode: string | null;
	/** Whether the opponent has a match list to field — not the list itself, and never its code. */
	combatReady: boolean;
	/** Whether the opponent has named a Leader — public, because Proceed is gated on both. */
	hasLeader: boolean;
	/**
	 * The Leader's M and INT from Scheme selection on, for the initiative roll. Which copy is the
	 * Leader never travels.
	 */
	leaderStats: { m: number | null; int: number | null } | null;
	/** Lobby readiness — public, since the leader's Start Game is gated on both seats. */
	ready: boolean;
	factionId: string | null;
	hasScheme: boolean;
	schemeRevealed: boolean;
	/** Only populated when revealed — unrevealed scheme content never travels to the opponent. */
	revealedScheme: ChosenScheme | null;
	checkedObjectiveCounts: Record<string, number>;
};

/** The per-seat filtered view the API returns. */
export type OnlineGameView = {
	id: string;
	status: OnlineGameStatus;
	seat: PlayerKey;
	phase: OnlineGamePhase;
	currentRound: number;
	season: string | null;
	missionId: string | null;
	pendingJoinNickname: string | null;
	roundSnapshots: Record<number, RoundSnapshot>;
	winner: PlayerKey | 'draw' | null;
	/** End-of-game summary — public once the game is finished. */
	resultSummary: ResultSummary | null;
	/** Full own-seat state including secrets. */
	self: OnlineSeatState;
	/** Filtered view of the other seat, or null while it is empty. */
	opponent: PublicSeatState | null;
};

export type OnlineGameEventType =
	| 'game-created'
	| 'join-requested'
	| 'join-accepted'
	| 'join-denied'
	| 'schemes-drawn'
	| 'scheme-chosen'
	| 'scheme-deleted'
	| 'seat-ready-toggled'
	| 'combat-army-set'
	| 'leader-assigned'
	| 'game-started'
	| 'scheme-revealed'
	| 'phase-changed'
	| 'objective-toggled'
	| 'scheme-box-toggled'
	| 'round-snapshotted'
	| 'game-finished'
	| 'game-closed';

/** Trimmed nickname, or null when empty/too long. */
export function normalizeNickname(raw: string): string | null {
	const trimmed = raw.trim();
	if (trimmed.length < 1 || trimmed.length > MAX_NICKNAME_LENGTH) return null;
	return trimmed;
}

function createEmptyProgress(): SeatProgress {
	return {
		checkedObjectiveCounts: {},
		scheme: null,
		schemeDraft: { factionId: null, intelligence: null },
		schemeRevealed: false
	};
}

export function createEmptySeat(
	nickname: string,
	tokenHash: string,
	army: PickedArmy
): OnlineSeatState {
	return {
		nickname,
		tokenHash,
		army,
		// A Standard registration is already a legal match list; a Roster one has to be cut down.
		combatArmy: pickedArmyFormat(army) === 'standard' ? army : null,
		leader: null,
		ready: false,
		progress: createEmptyProgress(),
		drawnSchemeIds: []
	};
}

/** What the creating player brings: the mission to play and the army they field. */
export type OnlineGameSetup = {
	season: string;
	missionId: string;
	army: PickedArmy;
};

export function createOnlineGame(
	id: string,
	leaderNickname: string,
	leaderTokenHash: string,
	createdAt: string,
	setup: OnlineGameSetup
): OnlineGameState {
	return {
		id,
		status: 'lobby',
		player1: createEmptySeat(leaderNickname, leaderTokenHash, setup.army),
		player2: null,
		pendingJoin: null,
		season: setup.season,
		missionId: setup.missionId,
		currentRound: MIN_ROUND,
		phase: 'playing',
		roundSnapshots: {},
		winner: null,
		resultSummary: null,
		createdAt,
		updatedAt: createdAt
	};
}

function updateSeat(
	state: OnlineGameState,
	seat: PlayerKey,
	updater: (s: OnlineSeatState) => OnlineSeatState
): OnlineGameState {
	const current = state[seat];
	if (!current) return state;
	return { ...state, [seat]: updater(current) };
}

/** Which seat owns a given (already hashed) token, if any. */
export function seatForTokenHash(state: OnlineGameState, tokenHash: string): PlayerKey | null {
	if (state.player1.tokenHash === tokenHash) return 'player1';
	if (state.player2?.tokenHash === tokenHash) return 'player2';
	return null;
}

// --- lobby: join flow ---

export function canRequestJoin(state: OnlineGameState): boolean {
	return state.status === 'lobby' && !state.player2 && !state.pendingJoin;
}

export function requestJoin(
	state: OnlineGameState,
	nickname: string,
	tokenHash: string,
	army: PickedArmy
): OnlineGameState {
	if (!canRequestJoin(state)) return state;
	return { ...state, pendingJoin: { nickname, tokenHash, army } };
}

/** Seat 2 takes over the pending request's nickname, token hash and army. */
export function acceptJoin(state: OnlineGameState): OnlineGameState {
	if (state.status !== 'lobby' || state.player2 || !state.pendingJoin) return state;
	return {
		...state,
		player2: createEmptySeat(
			state.pendingJoin.nickname,
			state.pendingJoin.tokenHash,
			state.pendingJoin.army
		),
		pendingJoin: null
	};
}

export function denyJoin(state: OnlineGameState): OnlineGameState {
	if (!state.pendingJoin) return state;
	return { ...state, pendingJoin: null };
}

// --- prep: the combat army ---

/** Whether a seat has a match list to field. */
export function isCombatReady(seat: OnlineSeatState): boolean {
	return seat.combatArmy !== null;
}

/** Both seats have a match list, which is what lets the leader leave the prep step. */
export function bothCombatReady(state: OnlineGameState): boolean {
	return isCombatReady(state.player1) && state.player2 !== null && isCombatReady(state.player2);
}

/**
 * Only a seat that registered a Roster army has anything to cut; a Standard registration is its
 * own combat army from the moment the seat is filled, and stays that way.
 */
export function canSetCombatArmy(state: OnlineGameState, seat: PlayerKey): boolean {
	if (state.status !== 'active' || state.phase !== 'prep') return false;
	const own = state[seat];
	return own !== null && pickedArmyFormat(own.army) === 'roster';
}

export function setCombatArmy(
	state: OnlineGameState,
	seat: PlayerKey,
	army: PickedArmy
): OnlineGameState {
	if (!canSetCombatArmy(state, seat)) return state;
	// A new list renumbers its copies on decode, so a leader chosen from the old one would dangle.
	return updateSeat(state, seat, (s) => ({ ...s, combatArmy: army, leader: null }));
}

/**
 * Any copy of the combat army may be the Leader — Stratagems are restricted *to* the Leader, not
 * the Leader to Stratagem-bearers — so the only precondition is having a list to choose from.
 */
export function canSetLeader(state: OnlineGameState, seat: PlayerKey): boolean {
	if (state.status !== 'active' || state.phase !== 'prep') return false;
	const own = state[seat];
	return own !== null && own.combatArmy !== null;
}

export function setLeader(
	state: OnlineGameState,
	seat: PlayerKey,
	leader: SeatLeader | null
): OnlineGameState {
	if (!canSetLeader(state, seat)) return state;
	return updateSeat(state, seat, (s) => ({ ...s, leader }));
}

/**
 * The Leader's M and INT are published from Scheme selection on, because that is where the
 * initiative roll that needs them sits. The Leader's identity never is.
 */
export function isLeaderStatsRevealed(state: OnlineGameState): boolean {
	return state.status !== 'lobby' && state.phase !== 'armies' && state.phase !== 'prep';
}

/** Both seats have named a Leader, which is what gives a seat its intelligence. */
export function bothLeadersAssigned(state: OnlineGameState): boolean {
	return state.player1.leader !== null && state.player2 !== null && state.player2.leader !== null;
}

export function canLeavePrep(state: OnlineGameState): boolean {
	return (
		state.status === 'active' &&
		state.phase === 'prep' &&
		bothCombatReady(state) &&
		bothLeadersAssigned(state)
	);
}

/**
 * Prep → Scheme setup. There is no way back: a cut is final once the table moves on.
 *
 * Both halves of the Scheme draft are derived here rather than typed in later: the faction from
 * the combat army, the intelligence from the Leader's declared INT. Nothing about the draw is left
 * for a client to choose, because the draw count is the one thing a player could otherwise
 * inflate.
 */
export function leavePrep(state: OnlineGameState): OnlineGameState {
	if (!canLeavePrep(state) || state.player2 === null) return state;
	const seed = (seat: OnlineSeatState): OnlineSeatState => ({
		...seat,
		progress: {
			...seat.progress,
			schemeDraft: {
				factionId: schemeFactionForArmy((seat.combatArmy ?? seat.army).factionId),
				intelligence: seat.leader?.int ?? null
			}
		}
	});
	return { ...state, phase: 'setup', player1: seed(state.player1), player2: seed(state.player2) };
}

// --- setup: faction and Scheme ---

/**
 * Scheme setup happens in the `setup` phase, after both seats have a match list and a Leader —
 * the army fixes the faction and the Leader fixes the intelligence, so there is nothing left to
 * choose but the Scheme itself.
 */
export function canEditSetup(state: OnlineGameState): boolean {
	return state.status === 'active' && state.phase === 'setup';
}

export function setSeatDrawnSchemes(
	state: OnlineGameState,
	seat: PlayerKey,
	schemeIds: string[]
): OnlineGameState {
	if (!canEditSetup(state)) return state;
	return updateSeat(state, seat, (s) => ({ ...s, drawnSchemeIds: schemeIds }));
}

export function canDrawSchemes(state: OnlineGameState, seat: PlayerKey): boolean {
	const current = state[seat];
	if (!canEditSetup(state) || !current) return false;
	const { factionId, intelligence } = current.progress.schemeDraft;
	return factionId !== null && intelligence !== null;
}

/** Only cards from the seat's own drawn hand may be chosen. */
export function canChooseSeatScheme(
	state: OnlineGameState,
	seat: PlayerKey,
	schemeId: string
): boolean {
	const current = state[seat];
	if (!canEditSetup(state) || !current) return false;
	const { factionId, intelligence } = current.progress.schemeDraft;
	return factionId !== null && intelligence !== null && current.drawnSchemeIds.includes(schemeId);
}

/** Picks a scheme from the seat's drawn hand and discards the rest of the hand. */
export function chooseSeatScheme(
	state: OnlineGameState,
	seat: PlayerKey,
	schemeId: string
): OnlineGameState {
	if (!canChooseSeatScheme(state, seat, schemeId)) return state;
	const { factionId, intelligence } = state[seat]!.progress.schemeDraft;
	return updateSeat(state, seat, (s) => ({
		...s,
		drawnSchemeIds: [],
		progress: { ...s.progress, scheme: chooseScheme(schemeId, factionId!, intelligence!) }
	}));
}

export function clearSeatScheme(state: OnlineGameState, seat: PlayerKey): OnlineGameState {
	if (!canEditSetup(state)) return state;
	return updateSeat(state, seat, (s) => ({ ...s, progress: { ...s.progress, scheme: null } }));
}

// --- lobby: readiness ---

/** Readiness is a lobby-only signal, and a seat may only flip its own. */
export function canToggleReady(state: OnlineGameState, seat: PlayerKey): boolean {
	return state.status === 'lobby' && state[seat] !== null;
}

export function toggleReady(state: OnlineGameState, seat: PlayerKey): OnlineGameState {
	if (!canToggleReady(state, seat)) return state;
	return updateSeat(state, seat, (s) => ({ ...s, ready: !s.ready }));
}

/** Both seats say they are set to start. */
export function bothReady(state: OnlineGameState): boolean {
	return state.player1.ready && state.player2 !== null && state.player2.ready;
}

/** Both seats have committed a Scheme. */
export function bothSchemesChosen(state: OnlineGameState): boolean {
	return (
		state.player1.progress.scheme !== null &&
		state.player2 !== null &&
		state.player2.progress.scheme !== null
	);
}

export function canStartGame(state: OnlineGameState): boolean {
	return (
		state.status === 'lobby' &&
		state.missionId !== null &&
		state.player2 !== null &&
		bothReady(state)
	);
}

/**
 * Start Game opens the army reveal, not round 1 — the rulebook shows both factions and rosters
 * before anyone builds a party from theirs.
 */
export function startGame(state: OnlineGameState): OnlineGameState {
	if (!canStartGame(state)) return state;
	return { ...state, status: 'active', currentRound: MIN_ROUND, phase: 'armies' };
}

// --- armies: the roster reveal ---

/**
 * A roster is revealed once the game is running, and stays revealed — including after it finishes,
 * so the statistics screen can still show what was brought. A Standard registration is never
 * revealed here: for it the registered list *is* the match list, and the rulebook keeps parties
 * secret until deployment.
 */
export function isRosterRevealed(state: OnlineGameState): boolean {
	return state.status !== 'lobby';
}

export function canLeaveArmies(state: OnlineGameState): boolean {
	return state.status === 'active' && state.phase === 'armies';
}

/** The reveal → preparation. There is no way back: what was shown stays shown. */
export function leaveArmies(state: OnlineGameState): OnlineGameState {
	if (!canLeaveArmies(state)) return state;
	return { ...state, phase: 'prep' };
}

export function canStartRounds(state: OnlineGameState): boolean {
	return state.status === 'active' && state.phase === 'setup' && bothSchemesChosen(state);
}

/**
 * Scheme setup → round 1. A running round carries no sub-phase: everything a round needs —
 * objectives, the reveal, scheme boxes — is editable within it, as on a physical table.
 */
export function startRounds(state: OnlineGameState): OnlineGameState {
	if (!canStartRounds(state)) return state;
	return { ...state, phase: 'playing' };
}

// --- active: rounds ---

/** A round is in progress: its objectives and scheme boxes are editable by their owners. */
export function isRoundRunning(state: OnlineGameState): boolean {
	return state.status === 'active' && state.phase === 'playing';
}

/**
 * Reveals this seat's scheme, immediately and permanently. The reveal is each player's own
 * decision at any moment of a running round — not an intent the leader commits on their behalf at
 * a phase change — so there is nothing to toggle and nothing to take back.
 */
export function canRevealSeatScheme(state: OnlineGameState, seat: PlayerKey): boolean {
	if (!isRoundRunning(state)) return false;
	const current = state[seat];
	return !!current?.progress.scheme && !current.progress.schemeRevealed;
}

export function revealSeatScheme(state: OnlineGameState, seat: PlayerKey): OnlineGameState {
	if (!canRevealSeatScheme(state, seat)) return state;
	return updateSeat(state, seat, (s) => ({
		...s,
		progress: { ...s.progress, schemeRevealed: true }
	}));
}

/** Objectives are editable only by their owner, at any point in a running round. */
export function setSeatObjectiveChecked(
	state: OnlineGameState,
	seat: PlayerKey,
	objectiveId: string,
	checkedCount: number,
	maxCount: number
): OnlineGameState {
	if (!isRoundRunning(state)) return state;
	const clamped = Math.max(0, Math.min(checkedCount, maxCount));
	return updateSeat(state, seat, (s) => ({
		...s,
		progress: {
			...s.progress,
			checkedObjectiveCounts: { ...s.progress.checkedObjectiveCounts, [objectiveId]: clamped }
		}
	}));
}

/** Scheme boxes are editable only by their owner, in a running round, and only once revealed. */
export function canScoreSeatScheme(state: OnlineGameState, seat: PlayerKey): boolean {
	if (!isRoundRunning(state)) return false;
	const current = state[seat];
	return !!current?.progress.scheme && current.progress.schemeRevealed;
}

export function setSeatSchemeChecked(
	state: OnlineGameState,
	seat: PlayerKey,
	checkedIncrements: number,
	maxIncrements: number
): OnlineGameState {
	if (!canScoreSeatScheme(state, seat)) return state;
	return updateSeat(state, seat, (s) => ({
		...s,
		progress: {
			...s.progress,
			scheme: setSchemeChecked(s.progress.scheme!, checkedIncrements, maxIncrements)
		}
	}));
}

/** Snapshots the current round's VP and opens the next one. Round 5 concludes instead. */
export function snapshotAndProceed(state: OnlineGameState, vp: RoundSnapshot): OnlineGameState {
	if (!isRoundRunning(state)) return state;
	if (state.currentRound >= MAX_ROUND) return state;
	return {
		...state,
		roundSnapshots: { ...state.roundSnapshots, [state.currentRound]: vp },
		currentRound: state.currentRound + 1,
		phase: 'playing'
	};
}

export function finishGame(state: OnlineGameState, vp: RoundSnapshot): OnlineGameState {
	if (!isRoundRunning(state) || state.currentRound !== MAX_ROUND) {
		return state;
	}
	const revealAll = (seat: OnlineSeatState): OnlineSeatState => {
		if (!seat.progress.scheme) return seat;
		return {
			...seat,
			progress: { ...seat.progress, schemeRevealed: true }
		};
	};
	const winner: PlayerKey | 'draw' =
		vp.player1 > vp.player2 ? 'player1' : vp.player2 > vp.player1 ? 'player2' : 'draw';
	const factionOf = (seat: OnlineSeatState | null): string | null =>
		seat?.progress.scheme?.factionId ?? seat?.progress.schemeDraft.factionId ?? null;
	const resultSummary: ResultSummary = {
		winner,
		finalVp: vp,
		roundsPlayed: state.currentRound,
		season: state.season,
		missionId: state.missionId,
		factions: { player1: factionOf(state.player1), player2: factionOf(state.player2) }
	};
	return {
		...state,
		roundSnapshots: { ...state.roundSnapshots, [state.currentRound]: vp },
		player1: revealAll(state.player1),
		player2: state.player2 ? revealAll(state.player2) : null,
		winner,
		resultSummary,
		status: 'finished'
	};
}

/** Leader closes/abandons the game — allowed from lobby or active, never overrides finished. */
export function closeGame(state: OnlineGameState): OnlineGameState {
	if (state.status === 'finished' || state.status === 'closed') return state;
	return { ...state, status: 'closed' };
}

// --- visibility ---

export function toPublicSeat(seat: OnlineSeatState, reveal: SeatReveal): PublicSeatState {
	const { progress } = seat;
	return {
		nickname: seat.nickname,
		army: {
			name: seat.army.name,
			factionId: seat.army.factionId,
			format: pickedArmyFormat(seat.army)
		},
		// The roster's contents are public once revealed — but only a roster's. A Standard
		// registration is the match list itself and stays secret until deployment.
		rosterCode: reveal.roster && pickedArmyFormat(seat.army) === 'roster' ? seat.army.code : null,
		ready: seat.ready,
		combatReady: seat.combatArmy !== null,
		hasLeader: seat.leader !== null,
		leaderStats:
			reveal.leaderStats && seat.leader !== null
				? { m: seat.leader.m, int: seat.leader.int }
				: null,
		factionId: progress.scheme?.factionId ?? progress.schemeDraft.factionId,
		hasScheme: progress.scheme !== null,
		schemeRevealed: progress.schemeRevealed,
		revealedScheme: progress.scheme && progress.schemeRevealed ? progress.scheme : null,
		checkedObjectiveCounts: progress.checkedObjectiveCounts
	};
}

/** The server answers state requests with this per-seat filtered view. */
export function viewForSeat(state: OnlineGameState, seat: PlayerKey): OnlineGameView | null {
	const self = state[seat];
	if (!self) return null;
	const opponent = seat === 'player1' ? state.player2 : state.player1;
	const reveal: SeatReveal = {
		roster: isRosterRevealed(state),
		leaderStats: isLeaderStatsRevealed(state)
	};
	return {
		id: state.id,
		status: state.status,
		seat,
		phase: state.phase,
		currentRound: state.currentRound,
		season: state.season,
		missionId: state.missionId,
		pendingJoinNickname: state.pendingJoin?.nickname ?? null,
		roundSnapshots: state.roundSnapshots,
		winner: state.winner,
		resultSummary: state.resultSummary,
		self,
		opponent: opponent ? toPublicSeat(opponent, reveal) : null
	};
}
